### ISSUE TITLE
error export fortune to excel

### ISSUE THREAD

**Issue by puviyan-jayaraman** [Corbe30/FortuneExcel#16]
1. Cannot read properties of undefined (reading 't') with some files and have not implemt styles line 60 in set
     at ExcelStyle.js:60:1
    at Array.every (<anonymous>)
    at ExcelStyle.js:20:1
    at Array.forEach (<anonymous>)
    at setStyleAndValue (ExcelStyle.js:16:1)
    at ExcelFile.js:89:1
    at Array.every (<anonymous>)
    at ExcelFile.js:83:1
    at step (ExcelFile.js:56:1)  getting this error 
![Screenshot 2024-12-20 151506](https://github.com/user-attachments/assets/44b9fdcd-cad9-4e57-a540-286d234b9e54)

**Comment by Corbe30** [comment]
@puviyan-jayaraman released v1.2.3, can you please check if the issue is resolved
